# Site settings
title: Diliaur's Github Page(s)! w00t!
email: Diliaur@hawaii.edu
description: > # this means to ignore newlines until "baseurl:"
  A twentysomething comp sci student messing around with programming things. 
  Hopefully I learn something along the way.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: diliaur
github_username:  diliaur

# Build settings
markdown: redcarpet
